# NumPy Exam

Import numpy as np and check your version.

In [1]:
import numpy as np
print(np.__version__)

1.20.3


**Q1:** Create a 1D array of numbers from `0` to `9` and save it as `Q1`.

In [2]:
Q1=np.arange(10)

**Q2:** Create a 1D array of numbers from `10` to `49` and save it as `Q2`.

In [3]:
Q2=np.arange(10,50)

**Q3:** Copy the `Q2` array and save it as `Q3`.  Reverse the values in the `Q3` array (first element becomes the last).

In [4]:
# make a copy of the previous array to prevent a "view" from being created
Q3 = Q2.copy()

Q3=Q3[::-1]

**Q4:** Create a `3x3` matrix with values ranging from `1` to `9` and save it as `Q4`.

In [5]:
Q4=np.arange(1,10).reshape(3,3)

**Q5:** Set a random seed of `42`. Create a `10x5` array with random values and save it as `Q5`.  Use [np.random.random()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html#).  As a check, your first row of the array should be: `[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864]`

In [6]:
np.random.seed(42) 

Q5=np.random.random((10,5))

**Q6:** Find the minimum and maximum values of above `Q5` array, rounding them to 4 decimal places.  Call the values `Q6A` and `Q6B` respectively. 

In [7]:
Q6A=round(Q5.min(), 4)

In [8]:
Q6B=round(Q5.max(), 4)

**Q7:** Find the mean value for the above `Q5` array, rounding to 4 decimal places.  Call this value `Q7`.

In [9]:
Q7=round(Q5.mean(),4)

**Q8:** Select all even numbers from the following array and call this output `Q8`.
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q8=arr[arr%2==0]

**Q9:** Make a copy of the `arr` array and call it `Q9`.  Replace all even numbers from `Q9` with `0`.

In [11]:
Q9 = arr.copy()

Q9[Q9%2==0]=0

**Q10:** Use the [where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) method to replace all odd numbers from the above `Q9` array with a `-1` and call it `Q10`.

In [12]:
Q10=np.where(Q9%2==1,-1,Q9)

**Q11** Reshape the above `arr` array to a `2x5` array and call it `Q11`.

In [13]:
Q11=arr.reshape((2,5))

**Q12:** Stack `arr1` and `arr2` (both given below) vertically and call this array `Q12`.

In [14]:
arr1 = np.arange(10).reshape((2,5))
arr2 = np.arange(10,20).reshape((2,5))

Q12=np.concatenate([arr1,arr2], axis=0)

**Q13:** Stack `arr1` and `arr2` horizontally and call this array `Q13`.

In [15]:
Q13=np.concatenate([arr1, arr2], axis=1)

**Q14:** Swap the first and second columns in the following array called `arr3` and save it as `Q14`.

In [16]:
arr3 = np.array([22,56,34,54,12,42,67,56,99]).reshape((3,3))
arr3

array([[22, 56, 34],
       [54, 12, 42],
       [67, 56, 99]])

In [17]:
Q14=arr3[:,[1,0,2]]

**Q15:** Swap rows 1 and 2 in the above `Q14` array and call it `Q15`.

In [18]:
Q15=Q14[[1,0,2],:]

**Q16:** Next, reverse the columns of the above `Q15` array and call it `Q16`.

In [19]:
Q16=Q15[:, ::-1]

**Q17:** Sort each row of the above `Q16` array from least to greatest and call it `Q17`.

In [20]:
Q17=np.sort(Q16, axis=1)

**Q18:** Sort each column of the above `Q17` array from the least to the greatest and call it `Q18`.

In [21]:
Q18=np.sort(Q17, axis=0)

**Q19:** Create a `1D` array called `Q19` of `100` values that range evenly between `[1 - 200]`.


In [22]:
Q19=np.linspace(1,200,100)

**Q20:** Reshape `Q19` to a `25x4` array and call it `Q20`.

In [36]:
Q20=Q19.reshape(25,4)
Q20

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [  9.04040404,  11.05050505,  13.06060606,  15.07070707],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 25.12121212,  27.13131313,  29.14141414,  31.15151515],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 41.2020202 ,  43.21212121,  45.22222222,  47.23232323],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

**Q21:** Index the first row of `Q20` and save this as `Q21`.

In [24]:
Q21=Q20[0]

**Q22:** Index the second column of `Q20` and save this as `Q22`.

In [25]:
Q22=Q20[:,1]

**Q23:** Index every other row of `Q20` starting from the first and save this as `Q23`.

In [26]:
Q23=Q20[::2]

**Q24:** Index the 3rd, 5th and 7th row of the `Q20` array can save this as `Q24`.

In [27]:
Q24=Q20[[2,4,6]]

**Q25:** Copy the `Q20` array and save it as `Q25`.  Select only the values below 50 from `Q25`, add 5 to these values, and then multiply by 2. The other values should remain unchanged and everything should be saved back to `Q25`.

In [28]:
# make a copy of Q20
Q25 = Q20.copy()

Q25[Q25<50]=(Q25[Q25<50]+5)*2

**Q26:** Add `Q20` and `Q25` and call the new array `Q26`.

In [29]:
Q26=Q20+Q25

**Q27:** What is the `shape` of `Q26`?  Save this as `Q27`.

In [30]:
Q27=Q26.shape

**Q28:** Cast `Q26` array as an `int64` data type.  Save this as `Q28`. What happens to the values?

In [31]:
Q28=Q26.astype('int64')

**Q29:** 
- Make a copy of the `Q28` array and call it `Q29`.  
- Select the first value in the first 5 rows in `Q29` and call this slice `arr_slice`.
- Update the second value in `arr_slice` to `42`. Before you check the results, will this update `Q29` or will it remain unchanged?

In [32]:
# make a copy of Q28
Q29 = Q28.copy()

arr_slice=Q29[0:5,0]
arr_slice[1]=42

**Q30:** Set all negative values in the `data` array (given below) to `0`.  For this exercise you will be updating the actual `data` array.

In [33]:
# create new array
data = np.array([2,-4,8,16,-32,-64,128])
data

array([  2,  -4,   8,  16, -32, -64, 128])

In [34]:
data[data<0]=0

Good work!