In [1]:
import numpy as np

In [27]:
np.random.seed(77)
Q1=np.random.randint(51, size =(8,6))
print(Q1)

[[23 31 20 20 43 37]
 [24 31 32 39 44 19]
 [32 36 36 47 14 15]
 [10  7 35  1 11 17]
 [ 6 20 37 33 40  1]
 [42  4 29 41 28  0]
 [28 40 25 37 11  3]
 [18 36 21 22 45 14]]


In [15]:
Q2=Q1[2:7,4:]

In [16]:
Q3=Q1[2:,3:5]

In [17]:
Q4=Q3.reshape((2,6))

In [18]:
Q5=Q4.reshape((3,4))

In [19]:
name = ['Janetta', 'Deb', 'Minato', 'Maurine', 'Niketas']
last = ['Lydia', 'Albin', 'Vanja', 'Peter', 'Justine']
height = [58, 68, 78, 77, 70]
age = [58, 50, 38, 57, 60]

In [23]:
Q6 = np.zeros(5, dtype = {'names':('Name', 'Last', 'Height', 'Age'),
                         'formats':('U20', 'U20', 'int16', 'int16')})

In [26]:
Q6['Name'] = name
Q6['Last'] = last
Q6['Height'] = height
Q6['Age'] = age