In [66]:
import numpy as np

In [95]:
np.random.seed(5)
p=np.random.randint(15, size =(20))

In [96]:
Q1=p[4]

In [97]:
Q2=p[8:]

In [98]:
Q3=p[1:18:2]

In [232]:
np.random.seed(6)
x=np.random.randint(15, size =(7, 8))
print(x)

[[10  9  3  4 10 13 10  0]
 [14  9  1 11 13  9 10  1]
 [12 14  4  1  8  2 12  4]
 [11  2  5 13 10  9  6  2]
 [11  5  5  1  4  5 14  0]
 [ 2  2  3  5 12 12 11  9]
 [ 5  2 10 14  7  8  5  6]]


In [230]:
Q4=x[5,3]
print(Q4)

5


In [231]:
Q5=x[:2,5:]
print(Q5)

[[13 10  0]
 [ 9 10  1]]


In [125]:
np.random.seed(10)
Q6=np.random.randint(15, size =(4, 5))

In [129]:
Q6[2,2]=4
Q7=Q6[1:,:3]

In [150]:
np.random.seed(8)
Q8=np.random.randint(15, size =(4, 5))

In [156]:
Q8_sub_copy=Q8[1:,:3].copy()
Q8_sub_copy[1,2]=4
Q9=Q8_sub_copy

In [161]:
np.random.seed(20)
a=np.random.randint(15, size =(2, 6))

In [162]:
Q10=a.reshape((4,3))

In [166]:
np.random.seed(15)
b=np.random.randint(15, size =(10))

In [165]:
Q11=b.reshape((10,1))

In [228]:
np.random.seed(9)
c=np.random.randint(15, size =(5,3))

In [229]:
c_sub_copy=c.copy()
Q12=c_sub_copy[3,0:]